### PR TITLE
feat: Generate animated GIF of board evolution

### LINKED ISSUE #45: Animated GIF showing evolution of the board
Hey @xiegeo 

This idea has been kicking around in my head for a while. Would be cool to create a GIF ([something like this](http://commit-sudoku.surge.sh/output.gif)) that shows evolution of the board from start to current state. 

I have a [PR](https://github.com/anishkny/commit-sudoku/pull/1) in my fork that does the following:

1. Get list of commits using `git log`
1. Get state of table at each commit using `git show $SHA:README.md`
1. Render each state in [Puppeteer](https://github.com/GoogleChrome/puppeteer) to PNG
1. Encode GIF from rendered PNGs

Its set to work on Travis. 

Thoughts?

### PR DESCRIPTION
**Pull request by anishkny**
Closes #45

### CODE REVIEW

**Comment by xiegeo** [comment]
Great work!

**Comment by anishkny** [comment]
We can basically show any commit history/meta data in the animation frames.

For commits, we are executing [`git log --reverse`](https://github.com/xiegeo/commit-sudoku/blob/master/animation/index.js#L19).

For each commit's meta info, we are executing: [`git show --format="format:%ci<br>%aE"`](https://github.com/xiegeo/commit-sudoku/blob/master/animation/index.js#L87). See [git pretty formats](https://git-scm.com/docs/pretty-formats).

**Comment by xiegeo** [comment]
How about use `git log --reverse --format=format:"%H %P"` then we can pick to only use commits with only one parent. This way we remove the merge author.

**Comment by anishkny** [comment]
I think `git log --no-merges` should get us the same thing. Will try it out.

**Pull request merged**
